project:
  type: website
  output-dir: C:/Users/pwang19.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "King Wang"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: resume.qmd
        text: Resume
      - href: publications.qmd
        text: Work & project
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

