---
title: "Resume"
---

# Education

-   **Master of Geomatics for Environmental Management (2024-2025)**

    -   Learned landscape ecology /management courses focuses on landscape quantification modeling and environmental management
    -   Apply geospatial expertise to encounter real-world scenario related to environmental management issues through labs, projects and workshops
    -   Took variety courses focused on analytical and quantitative methods in GIS, spatial statistics, spatial data analysis, and programming in R and Python

-   **Bachelor of Science Natural Resources Conservation: Major in Science and Management (2019-2023)**

    -   Taken variety courses regards to plants biology, soil science, hydrology, and wildlife management skill
    -   Gain strong knowledge on aquatic system (estuary and floodplains) of lower mainland BC and hand-on experience in variety of filed work
    -   Knowledge of computer skill applications in forestry and environmental management (R, ArcGIS, ENVI)
    -   Strong knowledge of different forest classification systems, including world forest classification systems, the BEC system, and ecosystem diagnosis in the field

# Research and projects

-   **Effectiveness Monitoring Plan for Active Restoration of Coho Salmon Habitat in an Oregon Watershed**

    Group project \| Advisor: Dr. Nolan Bett and Dr. Scott Hinch, UBC (Oct. 2023)

    -   Plan an active restoration program that focuses on limiting factors of coho salmon freshwater production
    -   Propose two relevant restoration activities with an appropriate effectiveness assessment monitoring plan

-   **Challenges of Greener Electricity Energy Implementation Around the World**

    Independent research \| Advisor: Dr. Emmanuel Ackom (May 2022)

    -   The main renewable electricity generation are highly variable and heavily depend on regional weather and geography

    -   Access to electricity is still a great challenge to some developing countries or regions

    -   Challenge of world’s electricity security due to high demand

# Field Experiences

-   **Fraser River Estuary Fish Abundance and Species Diversity (Sep. 2023)**

    -   Capture fish using beach seines in active Fraser River estuary research sites (Vancouver and Richmond)

    -   Identify and record information on different species of fish • Monitor compensation sites and reference sites • Provide report to compare the abundance and composition of Fraser River estuary fish at various marsh sites

-   **Fish Passage Through a Self-Regulating Floodgate in Colony Farms Coquitlam (Oct. 2023)**

    -   Gain hands-on experience in handling, measuring, and inserting PIT tags into juvenile salmon

    -   Handling minnow traps on the filed and identify the fish that has been captured by the traps

    -   Gain knowledge on current research project of “fish friendly” floodgate in Colony Farm

    -   Generate report of the fish passage behavior regarding to abiotic and biotic factors based on the data provided by Zachery Sherker, a PhD Candidate in the Pacific Salmon Ecology and Conservation Lab

-   **Restoration activities monitoring and their impacts in verity streams of Langley, BC (Nov. 2023)**

    -   Visit several streams in Langley and get insight into the restriction project of the streams

    -   Understand the current/past restoration project of the streams and the potential challenges or issues that still exist

    -   Report based on the restoration project that has been implemented and identified potential problems or improvement that could be make

# Teaching Assistantships

-   **UBC Forestry FRST100 Undergraduate Teaching Assistance (Sep. 2022 - Dec. 2022)**
    -   Grading homework, assignment, midterm, and final exam
    -   Monitor the course website
    -   Invigilation and respond to student emails, class discussion boards

# Institutional Service

-   **UBC Beaty Biodiversity Museum Educator (Oct. 2023 - Nov. 2024)**
    -   Represent the museum on the floor and provide support for special museum events and school programs
    -   Answer questions about the museum, provide variety activities, and have meaningful discussion with visitors about the significance of biodiversity
    -   Work with experienced museum staff, UBC biodiversity researchers, and learned about current biodiversity research through training programs
-   **UBC Reading Week Volunteers Community Storytelling (Feb. 2022)**
    -   Build a sense of belonging and community connection in Vancouver
    -   Gain organization and time management skills required for short project delivery
    -   Develop effective group working, communication, and collaboration skills
